### ISSUE TITLE
Preparing release with localized git fails

### ISSUE THREAD

**Issue by Swatinem** [getsentry/craft#75]
I have my system language set to `de-de`, which is also propagated to the shell (which I hate BTW).
Either way, git is actually localized, and craft apparently can’t deal with that.

running `git version 2.26.0`

```
> LANG=de_DE CRAFT_LOG_LEVEL=debug craft prepare 0.15.0
ℹ info Preparing to release the version: 0.15.0
✖ error Error: fatal: mehrdeutiges Argument 'release/0.15.0': unbekannter Commit oder Pfad existiert nicht
  im Arbeitsverzeichnis
  Benutzen Sie '--', um Pfade und Commits zu trennen, ähnlich wie:
  'git <Befehl> [<Commit>...] -- [<Datei>...]'

  at toError (/Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/promise.js:90:14)
  at /Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/promise.js:61:36
  at Git.<anonymous> (/Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/src/git.js:1090:18)
  at Function.Git.fail (/Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/src/git.js:1475:18)
  at fail (/Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/src/git.js:1433:20)
  at /Users/swatinem/.volta/tools/image/packages/@sentry/craft/0.9.2/node_modules/simple-git/src/git.js:1442:16
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

However, when I force no localization, it works just fine:

```
> LANG=C CRAFT_LOG_LEVEL=debug craft prepare 0.15.0
ℹ info Preparing to release the version: 0.15.0
ℹ info Created a new release branch: "release/0.15.0"
ℹ info Running the pre-release command...
… debug Spawning process:
  /bin/bash "scripts/bump-version.sh" "" "0.15.0"
… debug /bin/bash: Current version:
… debug /bin/bash: Bumping version: 0.15.0
… debug /bin/bash:
… debug /bin/bash:
ℹ info Committing the release changes...
… debug Commit message: "release: 0.15.0"
ℹ info Pushing the release branch "release/0.15.0"...
```

**Comment by Jean85** [comment]
Can confirm, I have the same issue with `it-IT` locale. The issue is here: https://github.com/getsentry/craft/blob/dd3b0667219403f98a1ebca637e9749149a1cda2/src/commands/prepare.ts#L125

Prepare should use `git show-ref --heads $BRANCH_NAME` to do the same check programmatically.
